name: Update README with Recent Activity

on:
  schedule:
    # Se ejecuta cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README

    steps:
      - uses: actions/checkout@v3

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'docs: update recent github activity'
          MAX_LINES: 7
          event_type: PushEvent # <--- AÑADE ESTA LÍNEA
